name: docker

# Build and push cryptoingestor docker images

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Python setup
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Install build dependencies
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest cython
          pip install aiohttp==3.8.1
          pip install pyyaml
          python setup.py install

      # Run tests
      - name: Run tests
        run: pytest tests/

  docker:
    needs: [ build ]
    name: build-docker-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build docker images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      # Build cryptoingestor docker image (develop)
      - name: Build cryptoingestor image (develop)
        if: ${{ steps.branch-name.outputs.current_branch == 'develop' }}
        id: docker_build_trader_develop
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/cryptoingestor:develop
          cache-from: type=gha
          cache-to: type=gha
      - name: Digest cryptoingestor image
        run: echo ${{ steps.docker_build_trader_develop.outputs.digest }}

